### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by frenck** [YeonV/home-assistant-addons#22]
This add-on seems to be a modified copy of the one from the community add-ons.

Please note that upstream has a license, which has been removed. This thus is in violation of the license.

**Comment by YeonV** [comment]
the god himself has spoken.

![image](https://user-images.githubusercontent.com/28861537/208752684-8a1cb8a3-3c22-4849-b19d-93ffe276e588.png)

![image](https://user-images.githubusercontent.com/28861537/208752733-e0f0b12b-5491-4202-816b-fe83eab173d1.png)

license added, url to original repo added

@frenck Thank you soo much for telling us master!!
Are my steps already enough?

**Comment by frenck** [comment]
Thanks! That's it 👍 

Happy Holidays 🎄 

../Frenck
