### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Spp595** [YeonV/home-assistant-addons#25]
Can't install ghcr.io/yeonv/amd64-addon-ledfx:2.0.62: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.62&fromImage=ghcr.io%2Fyeonv%2Famd64-addon-ledfx&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on 127.0.0.1:53: read udp 127.0.0.1:42914->127.0.0.1:53: read: connection refused")

**Comment by FragMenthor** [comment]
Can't install ghcr.io/yeonv/amd64-addon-ledfx:v2.0.67: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=v2.0.67&fromImage=ghcr.io%2Fyeonv%2Famd64-addon-ledfx&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by spiro-c** [comment]
Fixed need to work now

**Comment by Knottymister** [comment]
> Can't install ghcr.io/yeonv/amd64-addon-ledfx:v2.0.67: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=v2.0.67&fromImage=ghcr.io%2Fyeonv%2Famd64-addon-ledfx&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

Was there a fix for this?

**Comment by Spp595** [comment]
> > Can't install ghcr.io/yeonv/amd64-addon-ledfx:v2.0.67: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=v2.0.67&fromImage=ghcr.io%2Fyeonv%2Famd64-addon-ledfx&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
> 
> Was there a fix for this?

I do not recommend using this add-on.  There are a lot of problems with it and I never got it to work properly

**Comment by Knottymister** [comment]
Ah fair enough. You don't know of any alternatives currently do you?On 18 Jul 2023 08:42, Sp595 ***@***.***> wrote:


Can't install ghcr.io/yeonv/amd64-addon-ledfx:v2.0.67: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=v2.0.67&fromImage=ghcr.io%2Fyeonv%2Famd64-addon-ledfx&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

Was there a fix for this?

I do not recommend using this add-on.  There are a lot of problems with it and I never got it to work properly

**Comment by Spp595** [comment]
Unfortunately there are no alternatives

 I can't even run normal ledfx on my linux distro at all, the install
script is only suitable for ubuntu. Ledfx itself is mostly developed for
windows, although the go version is being developed.

ср, 19 июл. 2023 г., 17:08 Knottymister ***@***.***>:

> Ah fair enough. You don't know of any alternatives currently do you?On 18

**Comment by Knottymister** [comment]
No worries, thankyou for the reply. I'll stick to hyperion for my pi then!On 19 Jul 2023 13:31, Sp595 ***@***.***> wrote:
Unfortunately there are no alternatives



 I can't even run normal ledfx on my linux distro at all, the install

script is only suitable for ubuntu. Ledfx itself is mostly developed for

windows, although the go version is being developed.



ср, 19 июл. 2023 г., 17:08 Knottymister ***@***.***>:



> Ah fair enough. You don't know of any alternatives currently do you?On 18
