### ISSUE TITLE
LedFx Integration

### ISSUE THREAD

**Issue by Dejv311** [YeonV/home-assistant-addons#30]
Hi,
can you make this work with the HASS LedFx integration? The original repo from frenck does not work anymore and he seems to stopped developing it. Your fork unfortunately deleted the old tcp/ip comm layer and thus there is no automated way to control it from HA as far as I am aware.
Thank you

https://github.com/dmamontov/hass-ledfx

**Comment by spiro-c** [comment]
when you start the addon on the addon info you have the hostname of the addon add it with that hostname on port 8888
![image](https://github.com/YeonV/home-assistant-addons/assets/47688491/fd13b1c1-b02a-424c-bd4a-e8d871d373bc)
![image](https://github.com/YeonV/home-assistant-addons/assets/47688491/ad6a52fe-6035-4709-af06-a79cae1382c6)
![image](https://github.com/YeonV/home-assistant-addons/assets/47688491/8683f077-da4e-464d-bbfe-2ebd67c9339b)

**Comment by spiro-c** [comment]
I will close this like resolved
