### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Knottymister** [YeonV/home-assistant-addons#32]
Getting this message when I press install;

 Can't install ghcr.io/yeonv/aarch64-addon-ledfx:v2.0.69: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=v2.0.69&fromImage=ghcr.io%2Fyeonv%2Faarch64-addon-ledfx&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

Any help would be great!

**Comment by XxXCobraXxX** [comment]
I get the same error when i press install on an RPI4.

Can anyone help us please?

**Comment by XxXCobraXxX** [comment]
> Getting this message when I press install;
> 
> Can't install ghcr.io/yeonv/aarch64-addon-ledfx:v2.0.69: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=v2.0.69&fromImage=ghcr.io%2Fyeonv%2Faarch64-addon-ledfx&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
> 
> Any help would be great!

Do you find any solution for this problem?

**Comment by XxXCobraXxX** [comment]
> ![IMG_5925](https://user-images.githubusercontent.com/38837781/259834967-1886e1f8-27af-4c30-9233-968aeda36f61.jpeg)

or do you have an solution for this?

**Comment by spiro-c** [comment]
i just update the addon need to work now
