### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by zerlinux** [YeonV/home-assistant-addons#38]
Getting this message when I press install;

Can't install ghcr.io/yeonv/aarch64-addon-ledfx:v2.0.69: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=v2.0.69&fromImage=ghcr.io%2Fyeonv%2Faarch64-addon-ledfx&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

**Comment by spiro-c** [comment]
i just update the addon need to work now

**Comment by zerlinux** [comment]
I confirm that the installation was successful. Congratulations and thank you very much
